### ISSUE TITLE
keyboard support of touchscreen on pygame 2.0.0

### ISSUE THREAD

**Issue by werdeil** [Faylixe/pygame-vkeyboard#21]
Hello, since pygame 2.0.0 new events have appeared for touchscreen (FINGERDOWN, FINGERUP, FINGERMOTION) and touch action are no longer considered as mouse ones. As a consequence the keyboard doesn't seem to work.

I'm opening this issue and I'll try to see if I can provide a fix in a PR.

**Comment by spacether** [comment]
@werdeil should this issue be closed because the feature was merged?

**Comment by werdeil** [comment]
Yes I close it thanks
