### ISSUE TITLE
Workflow to build & publish failed

### ISSUE THREAD

**Issue by anxuae** [Faylixe/pygame-vkeyboard#23]
Hello @Faylixe ,

It seems that there is something wrong with your Pypi credentials in the build workflow: https://github.com/Faylixe/pygame-vkeyboard/runs/2428399765?check_suite_focus=true

Can you have a look?

Thanks
BR

**Comment by Faylixe** [comment]
Hello and sorry for the delay. I created a PyPI API token which is now the recommended way to authenticate for package upload, and updated the secrets accordingly, can you retry to upload your new version and let me know if this is working again ?

**Comment by anxuae** [comment]
Wonderful, it's working!
