### ISSUE TITLE
Changes to 'vkeyboard.py'

### ISSUE THREAD

**Issue by ohtrobinson** [Faylixe/pygame-vkeyboard#8]
Hi there.
Thank you so much for creating this keyboard! I'm creating an "operating system" that runs on a Raspberry pi with a touch screen. (I don't have the screen yet but I'm expecting it tomorrow!) So far, it's going well! Using your keyboard has made my life easier as I don't need to make my own.
Here are a few issues I have noticed and fixed:
- The keyboard only has an AZERTY layout. I have since added a QWERTY option (although have removed AZERTY because of my use case).
- Where I am from, the BACK key looks exactly like the Return key, and people might get confused, including myself. I have changed it to a new unicode icon which is more like the Backspace key on a keyboard.

Issues I am yet to sort:
- The keyboard doesn't fill the whole screen, which I need due to the small screen size I will be using. Please let me know how I might be able to change this!

Issues I can't fix!
- For whatever reason, an error occurs when importing directly. Here is the error:
![error](https://user-images.githubusercontent.com/52220544/63893440-14301c80-c9e2-11e9-8ed2-eac67ab82f29.png)
I have managed to "fix" this by putting this into my code:
`sys.path.append('/home/pi/.local/lib/python3.7/site-packages/pygame_vkeyboard')`
However, obviously, this isn't ideal. It does work, however.

I have also attached my customized "vkeyboard.py" if you want to have a look at what I've done.
I'd be happy to work with you to maintain this project if you would like me to.
Again, if you could help me resize the keyboard to fill the screen it would be greatly appreciated.

Thanks,
Ollie.
[customized_vkeyboard.zip](https://github.com/Faylixe/pygame_vkeyboard/files/3552954/customized_vkeyboard.zip)

**Comment by Faylixe** [comment]
Hello, could you retry with a new version (the new one on PyPi is 2.0.0 and should fix your problem)

**Comment by Faylixe** [comment]
I close this issues, new import scheme is available and should work as expected (please check updated `README.md`.
